version: '3.7'

services:
  usersdb:
    image: postgres:16.2-bookworm
    container_name: usersdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always
  usersapp:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersapp1:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp1
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersapp2:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp2
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersnginx:
    build: nginx
    expose:
      - 80
    depends_on:
      - usersapp
    container_name: usersnginx
    volumes:
      - ./users/static/:/users/static
      - ./users/:/home/app/users
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true
